name: Daily Tech News

on:
  schedule:
    - cron: '30 2 * * *'  # 8:00 AM IST (UTC+5:30)
  workflow_dispatch:        # allows manual run anytime

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests yagmail

      - name: Run script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python tech_news_summarizer.py
